//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixMedia.JointSpace.Tests.TestServerConfiguration {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixMedia.JointSpace.Tests.TestServerConfiguration.ResponseMessages", typeof(ResponseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;layer1&quot;: {
        ///		&quot;left&quot;: {
        ///			&quot;0&quot;: {
        ///				&quot;r&quot;: 104,
        ///				&quot;g&quot;: 91,
        ///				&quot;b&quot;: 99
        ///			},
        ///			&quot;1&quot;: {
        ///				&quot;r&quot;: 58,
        ///				&quot;g&quot;: 89,
        ///				&quot;b&quot;: 107
        ///			},
        ///			&quot;2&quot;: {
        ///				&quot;r&quot;: 23,
        ///				&quot;g&quot;: 98,
        ///				&quot;b&quot;: 130
        ///			},
        ///			&quot;3&quot;: {
        ///				&quot;r&quot;: 21,
        ///				&quot;g&quot;: 59,
        ///				&quot;b&quot;: 92
        ///			}
        ///		},
        ///		&quot;top&quot;: {
        ///			&quot;0&quot;: {
        ///				&quot;r&quot;: 23,
        ///				&quot;g&quot;: 49,
        ///				&quot;b&quot;: 79
        ///			},
        ///			&quot;1&quot;: {
        ///				&quot;r&quot;: 15,
        ///				&quot;g&quot;: 43,
        ///				&quot;b&quot;: 75
        ///			},
        ///			&quot;2&quot;: {
        ///				&quot;r&quot;: 7,
        ///				&quot;g&quot;: 37,
        ///				&quot;b&quot;: 68
        ///			},
        ///			&quot;3&quot;: {
        ///				&quot;r&quot;: 13,
        ///				&quot;g&quot;: 42,
        ///				&quot;b&quot;: 74 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AmbilightResponse {
            get {
                return ResourceManager.GetString("AmbilightResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;muted&quot;: false,
        ///	&quot;current&quot;: 14,
        ///	&quot;min&quot;: 1,
        ///	&quot;max&quot;: 60
        ///} ähnelt.
        /// </summary>
        internal static string AudioGetVolumne {
            get {
                return ResourceManager.GetString("AudioGetVolumne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;tv_all&quot;: {
        ///		&quot;name&quot;: &quot;All TV channels&quot;,
        ///		&quot;source&quot;: &quot;tv&quot;
        ///	},
        ///	&quot;tv_favourite&quot;: {
        ///		&quot;name&quot;: &quot;Favourite TV channels&quot;,
        ///		&quot;source&quot;: &quot;tv&quot;
        ///	},
        ///	&quot;tv_radio&quot;: {
        ///		&quot;name&quot;: &quot;Radio TV channels&quot;,
        ///		&quot;source&quot;: &quot;tv&quot;
        ///	},
        ///	&quot;tv_tv&quot;: {
        ///		&quot;name&quot;: &quot;Non-radio TV channels&quot;,
        ///		&quot;source&quot;: &quot;tv&quot;
        ///	},
        ///	&quot;sat_all&quot;: {
        ///		&quot;name&quot;: &quot;All satellite channels&quot;,
        ///		&quot;source&quot;: &quot;satellite&quot;
        ///	},
        ///	&quot;sat_favourite&quot;: {
        ///		&quot;name&quot;: &quot;Favourite satellite channels&quot;,
        ///		&quot;source&quot;: &quot;satellite&quot;
        ///	},
        ///	&quot;sat_radio&quot;: {
        ///		&quot;name&quot;: &quot;Radio satellite  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ChannelListGetAll {
            get {
                return ResourceManager.GetString("ChannelListGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///
        ///} ähnelt.
        /// </summary>
        internal static string EmptyChannelList {
            get {
                return ResourceManager.GetString("EmptyChannelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;current&quot;: &quot;internal&quot;
        ///} ähnelt.
        /// </summary>
        internal static string GetAmbilightModeResponse {
            get {
                return ResourceManager.GetString("GetAmbilightModeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;layers&quot;: 1,
        ///	&quot;left&quot;: 4,
        ///	&quot;top&quot;: 9,
        ///	&quot;right&quot;: 4,
        ///	&quot;bottom&quot;: 0
        ///} ähnelt.
        /// </summary>
        internal static string GetTopologyResponse {
            get {
                return ResourceManager.GetString("GetTopologyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;id&quot;: &quot;29&quot;
        ///} ähnelt.
        /// </summary>
        internal static string SourcesGetCurrent {
            get {
                return ResourceManager.GetString("SourcesGetCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;11&quot;: {
        ///		&quot;name&quot;: &quot;Kabel- /Antennen- Fernsehen&quot;
        ///	},
        ///	&quot;17&quot;: {
        ///		&quot;name&quot;: &quot;Satelliten- Fernsehen&quot;
        ///	},
        ///	&quot;28&quot;: {
        ///		&quot;name&quot;: &quot;HDMI 1&quot;
        ///	},
        ///	&quot;29&quot;: {
        ///		&quot;name&quot;: &quot;HDMI 2&quot;
        ///	},
        ///	&quot;30&quot;: {
        ///		&quot;name&quot;: &quot;HDMI 3&quot;
        ///	},
        ///	&quot;31&quot;: {
        ///		&quot;name&quot;: &quot;HDMI 4&quot;
        ///	},
        ///	&quot;32&quot;: {
        ///		&quot;name&quot;: &quot;SCART&quot;
        ///	},
        ///	&quot;33&quot;: {
        ///		&quot;name&quot;: &quot;Y Pb Pr&quot;
        ///	}
        ///} ähnelt.
        /// </summary>
        internal static string SourcesGetSources {
            get {
                return ResourceManager.GetString("SourcesGetSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;11&quot;: {
        ///		&quot;name&quot;: &quot;Kabel- /Antennen- Fernsehen&quot;
        ///	},
        ///	&quot;17&quot;: {
        ///		&quot;name&quot;: &quot;Satelliten- Fernsehen&quot;
        ///	},
        ///	&quot;28&quot;: {
        ///		&quot;name&quot;: &quot;HDMI 1&quot;
        ///	},
        ///	&quot;29&quot;: {
        ///		&quot;name&quot;: &quot;HDMI 2&quot;
        ///	},
        ///	&quot;30&quot;: {
        ///		&quot;name&quot;: &quot;HDMI 3&quot;
        ///	},
        ///	&quot;31&quot;: {
        ///		&quot;name&quot;: &quot;HDMI 4&quot;
        ///	},
        ///	&quot;32&quot;: {
        ///		&quot;name&quot;: &quot;SCART&quot;
        ///	},
        ///	&quot;33&quot;: {
        ///		&quot;name&quot;: &quot;Y Pb Pr&quot;
        ///	}
        ///} ähnelt.
        /// </summary>
        internal static string SourcesResponse {
            get {
                return ResourceManager.GetString("SourcesResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;country&quot;: &quot;Germany&quot;
        ///} ähnelt.
        /// </summary>
        internal static string SystemGetCountry {
            get {
                return ResourceManager.GetString("SystemGetCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;menulanguage&quot;: &quot;German&quot;,
        ///	&quot;name&quot;: &quot;55\&quot; Philips 8008&quot;,
        ///	&quot;country&quot;: &quot;Germany&quot;,
        ///	&quot;serialnumber&quot;: &quot;AB1C2345678901&quot;,
        ///	&quot;softwareversion&quot;: &quot;QF2EU-0.173.67.0&quot;,
        ///	&quot;model&quot;: &quot;55PFL8008S/12&quot;
        ///} ähnelt.
        /// </summary>
        internal static string SystemGetDetails {
            get {
                return ResourceManager.GetString("SystemGetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;menulanguage&quot;: &quot;German&quot;
        ///} ähnelt.
        /// </summary>
        internal static string SystemGetMenuLanguage {
            get {
                return ResourceManager.GetString("SystemGetMenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;model&quot;: &quot;55PFL8008S/12&quot;
        ///} ähnelt.
        /// </summary>
        internal static string SystemGetModel {
            get {
                return ResourceManager.GetString("SystemGetModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;name&quot;: &quot;55\&quot; Philips 8008&quot;
        ///} ähnelt.
        /// </summary>
        internal static string SystemGetName {
            get {
                return ResourceManager.GetString("SystemGetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;serialnumber&quot;: &quot;AB1C2345678901&quot;
        ///} ähnelt.
        /// </summary>
        internal static string SystemGetSerialNumber {
            get {
                return ResourceManager.GetString("SystemGetSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;softwareversion&quot;: &quot;QF2EU-0.173.67.0&quot;
        ///} ähnelt.
        /// </summary>
        internal static string SystemGetVersionNumber {
            get {
                return ResourceManager.GetString("SystemGetVersionNumber", resourceCulture);
            }
        }
    }
}
